# Generated by Django 5.0.4 on 2024-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_review_time_date_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='negative_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='neutral_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='positive_score',
            field=models.FloatField(default=0),
        ),
    ]
